# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- AzureDevOpsPipeline

variables:
  Solution.Name: 'Solution/HelloPCF'
  Version.Revision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  Version.Major: 1
  Version.Minor: 0


name: '$(Build.DefinitionName) $(Version.Major).$(Version.Minor).$(Date:yy)$(DayOfYear).$(Version.Revision)'

pool:
  vmImage: 'windows-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: 'run build --if-present'

- task: MSBuild@1
  displayName: 'Run MSBuild'
  inputs:
    solution: '$(solution.name)'
    configuration: 'Release'
    msbuildArguments: '/restore /t:rebuild'

- task: CopyFiles@2
  displayName: 'Copy managed and unmanaged files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\$(Solution.Name)\bin\Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'PCF Solutions'
    publishLocation: 'pipeline'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
