# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- AzureDevOpsPipeline

variables:
  solution.name: 'Solution/HelloPCF'

pool:
  vmImage: 'windows-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'ci'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build --if-present'

- task: MSBuild@1
  inputs:
    solution: '$(solution.name)'
    msbuildArguments: '/restore /t:rebuild'


- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
